# Generated by Django 4.2.29 on 2026-03-10 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('presion_arterial', models.CharField(blank=True, help_text='Ej: 120/80', max_length=10)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, help_text='lpm', null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('saturacion_o2', models.PositiveSmallIntegerField(blank=True, help_text='%', null=True)),
                ('subjetivo', models.TextField(help_text='Motivo de consulta y síntomas referidos')),
                ('objetivo', models.TextField(help_text='Exploración física y hallazgos')),
                ('diagnostico', models.TextField(help_text='Diagnóstico (puede incluir CIE-10)')),
                ('plan', models.TextField(help_text='Plan de tratamiento y recomendaciones')),
                ('evolucion', models.TextField(blank=True, help_text='Notas de evolución adicionales')),
                ('proxima_cita', models.DateField(blank=True, help_text='Fecha sugerida para próxima cita', null=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consulta', to='citas.cita')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='citas.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consultas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(help_text='Ej: 500 mg', max_length=100)),
                ('frecuencia', models.CharField(help_text='Ej: Cada 8 horas', max_length=100)),
                ('duracion', models.CharField(help_text='Ej: 7 días', max_length=100)),
                ('indicaciones', models.TextField(blank=True, help_text='Instrucciones especiales')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='consultas.consulta')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'recetas',
                'ordering': ['consulta', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['paciente', 'fecha'], name='consultas_pacient_970893_idx'),
        ),
    ]
