# Generated by Django 4.2.29 on 2026-03-10 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'db_table': 'doctores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('duracion_min', models.PositiveSmallIntegerField(default=30, help_text='Duración en minutos')),
                ('tipo', models.CharField(choices=[('PRIMERA_VEZ', 'Primera vez'), ('SEGUIMIENTO', 'Seguimiento'), ('URGENCIA', 'Urgencia'), ('REVISION', 'Revisión de resultados')], default='PRIMERA_VEZ', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada'), ('NO_ASISTIO', 'No asistió')], db_index=True, default='PENDIENTE', max_length=15)),
                ('motivo', models.TextField(blank=True, help_text='Motivo de consulta')),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas de administración')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora', 'estado'], name='citas_fecha_h_117be1_idx'), models.Index(fields=['paciente', 'estado'], name='citas_pacient_466fc4_idx'), models.Index(fields=['doctor', 'fecha_hora'], name='citas_doctor__383496_idx')],
            },
        ),
    ]
