# Generated by Django 4.2.29 on 2026-03-11 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002 citas fixed '),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_fecha_h_117be1_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_pacient_466fc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_doctor__383496_idx',
        ),
    ]
