# Generated by Django 4.2.29 on 2026-03-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_horariodoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='informe_doctor',
            field=models.TextField(blank=True, verbose_name='Informe del doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Horario de atención (texto)'),
        ),
        migrations.AlterField(
            model_name='horariodoctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
