# Generated by Django 4.2.29 on 2026-03-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_cita_informe_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='citas.doctor'),
        ),
    ]
