# Generated by Django 4.2.29 on 2026-03-10 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(db_index=True, max_length=100)),
                ('apellidos', models.CharField(db_index=True, max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True, help_text='Lista de alergias conocidas')),
                ('antecedentes', models.TextField(blank=True, help_text='Antecedentes heredofamiliares')),
                ('enfermedades_cronicas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['apellidos', 'nombres'], name='pacientes_apellid_73ca1c_idx'), models.Index(fields=['curp'], name='pacientes_curp_a9f645_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArchivoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PDF', 'Documento PDF'), ('IMG', 'Imagen'), ('LAB', 'Resultado de Laboratorio'), ('RX', 'Radiografía'), ('OTRO', 'Otro')], max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='archivos_clinicos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Archivo Clínico',
                'verbose_name_plural': 'Archivos Clínicos',
                'db_table': 'archivos_clinicos',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
