# Generated by Django 4.2.29 on 2026-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad (8 dígitos)', max_length=8, null=True, verbose_name='DNI'),
        ),
    ]
